spring.application.name=RealLife
spring.data.mongodb.uri=mongodb+srv://raushankumar98667_db_user:raushan1234@springbootcrash.dgp9u0w.mongodb.net/?college-api=SpringBootCrash
server.port=8080
spring.autoconfigure.exclude=org.springframework.boot.security.servlet.SecurityAutoConfiguration